apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-swck
  namespace: zq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java-swck
  template:
    metadata:
      labels:
        app: demo-java-swck
        swck-java-agent-injected: "true" # 开启当前 Pod 的自动注入，通用 agent 配置由 swagent.yaml 统一维护。
    spec:
      containers:
        - name: app
          image: registry.cn-hangzhou.aliyuncs.com/zhengqing/test:demo-java-swck
          imagePullPolicy: Always
          env:
            - name: server.port
              value: "666"
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app'] # 从当前 Pod 的 app 标签动态生成 SkyWalking 服务名。
          ports:
            - name: http
              containerPort: 666
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-swck
  namespace: zq
spec:
  selector:
    app: demo-java-swck
  type: LoadBalancer
  ports:
    - name: http
      port: 30080
      targetPort: 666
      protocol: TCP
