apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-otel-go
  namespace: signoz-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-k8s-otel-go
  template:
    metadata:
      labels:
        app: demo-k8s-otel-go
    spec:
      containers:
        - name: app
          image: registry.cn-hangzhou.aliyuncs.com/zhengqingya/test:demo-k8s-otel-go
          imagePullPolicy: Always
          env:
            - name: HTTP_ADDR
              value: ":18082"
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.signoz.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "10000"
          ports:
            - name: http
              containerPort: 18082
---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-otel-go
  namespace: signoz-demo
spec:
  selector:
    app: demo-k8s-otel-go
  type: LoadBalancer
  ports:
    - name: http
      port: 30084
      targetPort: 18082
      protocol: TCP
