apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-agent-java
  namespace: k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-k8s-agent-java
  template:
    metadata:
      labels:
        app: demo-k8s-agent-java
        swck-java-agent-injected: "true"
    spec:
      containers:
        - name: app
          image: registry.cn-hangzhou.aliyuncs.com/zhengqingya/test:demo-agent-java
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-agent-java
  namespace: k8s-agent
spec:
  selector:
    app: demo-k8s-agent-java
  type: LoadBalancer
  ports:
    - name: http
      port: 31082
      targetPort: 80
      protocol: TCP
