apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-agent-php
  namespace: k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-agent-php
  template:
    metadata:
      labels:
        app: demo-agent-php
    spec:
      containers:
        - name: app
          image: registry.cn-hangzhou.aliyuncs.com/zhengqingya/test:demo-agent-php
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking-oap.skywalking.svc.cluster.local:11800"
          ports:
            - name: http
              containerPort: 18083
---
apiVersion: v1
kind: Service
metadata:
  name: demo-agent-php
  namespace: k8s-agent
spec:
  selector:
    app: demo-agent-php
  type: LoadBalancer
  ports:
    - name: http
      port: 31085
      targetPort: 18083
      protocol: TCP
